### ISSUE TITLE
Clean up this Repository

### ISSUE THREAD

**Issue by corvidfox** [corvidfox/Testing-Connections#1]
The repository is a bit of a mess.

- [x] Create an R and Python Folder
- [x] Separate files accordingly

We should consider:

- [x] Update ReadMe
- [x] Add R analysis of data in our demo_data source file
- [x] Show gitignore to keep PHI out of the repository!

**Comment by MMExampleAccount** [comment]
Can you tell me a bit more about this issue? I think I should be able to resolve this.

**Comment by corvidfox** [comment]
I really appreciate that, @MMExampleAccount! I'll try to add you as a collaborator on this task.
